# Generated by Django 4.2 on 2024-12-02 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UploadFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('is_deleted', models.BooleanField(blank=True, default=False, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='')),
                ('thumbnail_file', models.ImageField(blank=True, null=True, upload_to='')),
                ('file_tags', models.CharField(blank=True, max_length=128, null=True)),
                ('file_url', models.CharField(blank=True, max_length=128, null=True)),
                ('file_name', models.CharField(blank=True, max_length=128, null=True)),
                ('bucket_name', models.CharField(default='chat-bucket', max_length=128)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('is_deleted', models.BooleanField(blank=True, default=False, null=True)),
                ('title', models.CharField(max_length=128)),
                ('slug', models.SlugField(allow_unicode=True)),
                ('level', models.IntegerField(default=0)),
                ('file_url', models.CharField(blank=True, max_length=250, null=True)),
                ('files', models.ManyToManyField(blank=True, to='basement.uploadfile')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='basement.category')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
